version: '3'

services:
  json-server:
    image: codfish/json-server
    command: npm run dev
    ports:
      - 8000:80
    volumes:
      - ./db.js:/app/db.js
    networks:
      - json-server-network

networks:
  json-server-network: